require:
  - rubocop-rails
  - rubocop-rspec

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: enable
  SuggestExtensions: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/**/*

Rails/LexicallyScopedActionFilter:
  Exclude:
    - app/controllers/**/*

RSpec/MultipleMemoizedHelpers:
  Max: 8

RSpec/NestedGroups:
  Max: 4
