version: '3.8'

x-defaults: &defaults
  build: .
  environment:
    - POSTGRES_HOST=db
    - REDIS_HOST=redis
  env_file:
    - ./.env
  depends_on:
    - db
    - redis
  volumes:
    - .:/app
    - /etc/localtime:/etc/localtime:ro

services:
  app:
    <<: *defaults
    container_name: planner_app
    ports:
      - 3000:3000

  sidekiq:
    <<: *defaults
    container_name: planner_sidekiq
    command: bundle exec sidekiq -C config/sidekiq.yml

  db:
    container_name: postgres_db
    image: postgres:15
    env_file:
     - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    container_name: redis_db
    image: redis:7.2.4
    env_file:
      - ./.env
    volumes:
      - redis-data:/var/lib/redis/data

volumes:
  postgres-data:
  redis-data:
